Food_Stock_Exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mainViews
from registration import views as registration


urlpatterns = [
    path('vv21/admin/', admin.site.urls),
    path('', include('web.urls')),
    path('register/', registration.registerPage, name="registration"),
    path('accounts/login/', registration.registerPage1, name="registration"),
    path('home/', include('main.urls')),
    path("home/<int:pk>/", mainViews.chatroom, name="chatroom"),
    path("home/ajax1/<int:pk>/", mainViews.ajax_load_messages, name="chatroom-ajax"),
    path("menu/<str:cuisine>", mainViews.showMenu, name="showMenu"),
    path("barmenu/<str:drinktype>", mainViews.showBarMenu, name="showBarMenu"),
    path("barmenu/ajax/<str:drinktype>", mainViews.showBarMenu_ajax, name="showBarMenu_ajax"),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    # path('', views.home, name = 'homePage'),
    # path('admin/', admin.site.urls),
    path("order/", views.order, name="order"),
    path("<int:pk>/", views.chatroom, name="chatroom"),
    path("ajax/<int:pk>/", views.ajax_load_messages1, name="bot-message"),

]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
  path("", views.project, name="project"),
  path("stock/", views.stock, name="stock"),
  path("stock/ajax", views.stock_load_ajax, name="stock_load_ajax"),
]

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core import validators


# Create your models here.

User = get_user_model()

class foodMenu(models.Model):
    foodtype = (
        ("1", "Veg"),
        ("2", "Non-Veg"),
    )

    all_cuisine = (
        ("1", "Soup"),
        ("2", "Salad"),
        ("3", "Appetizers"),
        ("4", "Italian Mainfare"),
        ("5", "Mexican Mainfare"),
        ("6", "Pastas"),
        ("7", "Pizzas"),
        ("8", "Rice"),
        ("9", "Fondue"),
        ("10", "Desserts"),
    )
    
    cuisine = models.CharField(choices=all_cuisine, max_length=50, blank=True)
    name = models.CharField(max_length=50, blank=True)
    price = models.IntegerField(null=True)
    foodtype = models.CharField(choices=foodtype, max_length=10)
    newest = models.BooleanField(default=False)
    recommended = models.BooleanField(default=False)
    ratings = models.IntegerField(validators=[
                              validators.MinValueValidator(1), validators.MaxValueValidator(5)], null=True, default=4)

    def __str__(self):
      return self.get_cuisine_display() + " - " + self.name

    class Meta:
      verbose_name_plural = "Food Menu"

class barMenu(models.Model):
    all_drinktype = (
        ("1", "Beer"),
        ("2", "Cocktail"),
        ("3", "Gin"),
        ("4", "Red Wine"),
        ("5", "Sparkling Wine"),
        ("6", "Vodka"),
        ("7", "Whiskey"),
        ("8", "White Wine"),
    )
    drinktype = models.CharField(choices=all_drinktype, max_length=50, blank=True)
    name = models.CharField(max_length=50, blank=True)
    current_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    old_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    tot_qty = models.IntegerField(null=True)
    actual_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    savings = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    low = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    high = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    className = models.CharField(max_length=50, blank=True)
    recommended_drink = models.BooleanField(default=False) 

    def __str__(self):
        return self.get_drinktype_display() + " - " + self.name

    class Meta:
        verbose_name_plural = "Bar Menu"


class ordered(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    dish_name = models.CharField(max_length=50, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    qty = models.IntegerField(null=True)
    cooked = models.BooleanField(default=False)

    def __str__(self):
      return self.dish_name

    class Meta:
      verbose_name_plural = "Ordered"


class Message(models.Model):

    sender = models.ForeignKey(User, related_name="sent_messages", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="received_messages", on_delete=models.CASCADE)
    message = models.TextField()
    className = models.CharField(max_length=50, blank=True)
    seen = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_created",)

main/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from .models import User, Message, foodMenu, barMenu, ordered
from django.http import HttpResponseRedirect
from django.db.models import Q
import json
from decimal import Decimal
from .chatbot import *
from django.core import serializers

# Create your views here.

dname = ""
dqty = ""
dprice = ""
dsavings = ""
other_user = ""
pk1 = 0

def showMenu(request, cuisine):
    global other_user
    all_cuisine = (
        ("1", "Soup"),
        ("2", "Salad"),
        ("3", "Appetizers"),
        ("4", "Italian Mainfare"),
        ("5", "Mexican Mainfare"),
        ("6", "Pastas"),
        ("7", "Pizzas"),
        ("8", "Rice"),
        ("9", "Fondue"),
        ("10", "Desserts"),
    )

    for cuisine1 in all_cuisine:
        if cuisine1[1] == cuisine:
            cuisinename = cuisine
            cuisine = cuisine1[0]
            break
    
    if request.method == "POST":
        dname = request.POST['dname']
        dqty = request.POST['dqty']
        dprice = request.POST['dprice']
        totamt = int(dprice) * int(dqty)
        m = ordered.objects.create(
            user = request.user,
            dish_name=dname, 
            price=totamt, 
            qty=dqty, 
            cooked=False
            )

        msgDish = dname + " is ordered!"
        m1 = Message.objects.create(receiver=request.user, sender=other_user, message=msgDish, className="bot")

    all_dish = foodMenu.objects.all().filter(cuisine__icontains=cuisine)
    return render(request, "main/menu.html", {"all_dish": all_dish, "cuisine":cuisinename})


def showBarMenu(request, drinktype):
    all_drinktype = (
        ("1", "Beer"),
        ("2", "Cocktail"),
        ("3", "Gin"),
        ("4", "Red Wine"),
        ("5", "Sparkling Wine"),
        ("6", "Vodka"),
        ("7", "Whiskey"),
        ("8", "White Wine"),
    )
    for drink in all_drinktype:
        if drink[1] == drinktype:
            drinkname = drinktype
            drinktype = drink[0]
            break
    all_drinks = barMenu.objects.all().filter(drinktype__icontains=drinktype)
    return render(request, "main/barmenu.html", {"all_drinks": all_drinks, "drinktype":drinkname})

def showBarMenu_ajax(request, drinktype):
    if request.method == 'GET':
        all_drinktype = (
            ("1", "Beer"),
            ("2", "Cocktail"),
            ("3", "Gin"),
            ("4", "Red Wine"),
            ("5", "Sparkling Wine"),
            ("6", "Vodka"),
            ("7", "Whiskey"),
            ("8", "White Wine"),
        )
        for drink in all_drinktype:
            if drink[1] == drinktype:
                drinkname = drinktype
                drinktype = drink[0]
                break
            
        all_drinks = barMenu.objects.all().filter(drinktype__icontains=drinktype)

        all_drinks = serializers.serialize("json", all_drinks)

        all_drinks = json.loads(all_drinks)

        return JsonResponse(all_drinks, safe=False)


@login_required
def chatroom(request, pk: int):
    global dname, dqty, dprice, dsavings, other_user, pk1
    
    all_cuisine = (
        ("1", "Soup"),
        ("2", "Salad"),
        ("3", "Appetizers"),
        ("4", "Italian Mainfare"),
        ("5", "Mexican Mainfare"),
        ("6", "Pastas"),
        ("7", "Pizzas"),
        ("8", "Rice"),
        ("9", "Fondue"),
        ("10", "Desserts"),
    )

    all_drinktype = (
        ("1", "Beer"),
        ("2", "Cocktail"),
        ("3", "Gin"),
        ("4", "Red Wine"),
        ("5", "Sparkling Wine"),
        ("6", "Vodka"),
        ("7", "Whiskey"),
        ("8", "White Wine"),
    )

    allcuisine = foodMenu.objects.order_by('cuisine').values('cuisine').distinct()
    for i in allcuisine:
        number = int(i['cuisine']) - 1
        i['cuisine'] = all_cuisine[number][1]

    alldrinks = barMenu.objects.order_by('drinktype').values('drinktype').distinct()
    
    for i in alldrinks:
        number = int(i['drinktype']) - 1
        i['drinktype'] = all_drinktype[number][1]

    all_dishes = foodMenu.objects.values()

    for i in all_dishes:
        number = int(i['cuisine']) - 1
        i['cuisine'] = all_cuisine[number][1]

    all_dishes = json.dumps(list(all_dishes))

    all_ordered = ordered.objects.all()

    newest = foodMenu.objects.all().filter(newest=True)

    for i in newest:
        number = int(i.cuisine) - 1
        i.cuisine = all_cuisine[number][1]


    recommended = foodMenu.objects.all().filter(recommended=True)

    for i in recommended:
        number = int(i.cuisine) - 1
        i.cuisine = all_cuisine[number][1]


    recommended_drink = barMenu.objects.all().filter(recommended_drink = True)

    for i in recommended_drink:
        number = int(i.drinktype) - 1
        i.drinktype = all_drinktype[number][1]

    other_user = get_object_or_404(User, pk=pk)

    pk1 = request.user.pk
    request_user = request.user.username

    messages = Message.objects.filter(
        Q(receiver=request.user, sender=other_user)
    )
    messages.update(seen=True)
    messages = messages | Message.objects.filter(
        Q(receiver=other_user, sender=request.user))



    if request.method == "POST":

        dname = request.POST['dname']
        dqty = request.POST['dqty']
        dprice = request.POST['dprice']
        dsavings = request.POST['dsavings']
        dtype = request.POST['dtype']

        # print(dname, dqty, dprice, dsavings)
        # print("------------------------")

        msg = ""
        
        if Decimal(dsavings) > 0:
            msg = "Low"
            msg_className = "accepted"
        elif Decimal(dsavings) == 0:
            msg = "Neutral"
            msg_className = "accepted"
        else:
            msg = "High"
            msg_className = "rejected"

        msg1 = str(dtype)

        print(msg1)
        print(msg_className, Decimal(dsavings) > 0)

        msg_price = send_reply_price(msg)
        msg_drink = send_reply_drink(msg1)
        msg_confirm = dname + " ( " + dqty + " )" + " for " + dprice + " each."

        bot_sends_msg = msg_confirm + " |" + str(msg_drink) + "  |" + str(msg_price)

        print(str(msg_drink) + " " + str(msg_price))

        m = Message.objects.create(receiver=request.user, sender=other_user, message=bot_sends_msg, className=msg_className)

        # x, y = bargaing(dname, dqty)
        
        
    # x, y = bargaing("White wine", 3)
    # print(x)
    # print(y)
        
    return render(request, "main/home.html", {"other_user": other_user, "request_user": request_user, "messages": messages, 'allcuisine': allcuisine, 'alldrinks': alldrinks, "newest": newest, "recommended": recommended, "recommended_drink": recommended_drink, "all_dishes": all_dishes, "all_ordered": all_ordered})

@login_required
def ajax_load_messages(request, pk):
    global dname, dqty, dprice, dsavings
    other_user = get_object_or_404(User, pk=pk)
    messages = Message.objects.filter(seen=False).filter(
        Q(receiver=request.user, sender=other_user)
    )
    message_list = [{
        "sender": message.sender.username,
        "message": message.message,
        "className": message.className,
        "sent": message.sender == request.user
    } for message in messages]
    messages.update(seen=True)    
    if request.method == "POST":
        message = json.loads(request.body)
        m = Message.objects.create(receiver=other_user, sender=request.user, message=message, className="user_chat")
        message_list.append({
                "sender": request.user.username,
                "message": m.message,
                "sent": True,
                "className": "user_chat",
            })

        if message == "Deal":
            totamt = Decimal(dprice) * int(dqty)
            m = ordered.objects.create(
                user = request.user,
                dish_name=dname, 
                price=Decimal(totamt), 
                qty=int(dqty), 
                cooked=False
                )
            x = bargaing(dname, int(dqty))
            print(x)
        else:
            m = Message.objects.create(receiver=request.user, sender=other_user, message="Order Cancelled", className="bot")
            
    print(message_list)
    return JsonResponse(message_list, safe=False)

@login_required
def ajax_load_messages1(request, pk):
    other_user = get_object_or_404(User, pk=pk)

    messages = Message.objects.filter(seen=False).filter(
        Q(receiver=request.user, sender=other_user)
    )

    message_list = [{
        "sender": "foodmarket",
        "message": message.message,
        "className": message.className,
        "sent": message.sender == request.user
    } for message in messages]
    messages.update(seen=True)
    
    if request.method == "POST":
        message = json.loads(request.body)
        bot_message, className = send_reply_drink(message)
        print(className)
        m = Message.objects.create(receiver=request.user, sender=other_user, message=bot_message, className=className)
        message_list.append({
            "sender": "foodmarket",
            "message": bot_message,
            "sent": True,
            "className": "bot",
        })
        print(bot_message)
    return JsonResponse(message_list, safe=False)


def search_view(request):
    if request.method == "POST":
        search_word = request.POST['data']
        print(search_word)
    return render(request, "main/home.html")


def order(request):
    pk1 = request.user.pk
    print(pk1)
    all_ordered = ordered.objects.all().filter(user = pk1)
    return render(request, "main/order.html", {"all_ordered": all_ordered})

main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Add CSS Files Here -->

	<!-- 'styles.css' At The Top -->

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
		integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
		crossorigin="anonymous" />

	<link rel="stylesheet" href="{% static '/css/styles.css' %}" />
	<link rel="stylesheet" href="{% static '/css/home.css' %}" />
	<link rel="stylesheet" href="{% static '/css/explore.css' %}" />
	<link rel="stylesheet" href="{% static '/css/explore.css' %}" />
	<link rel="stylesheet" href="{% static '/css/chat.css' %}" />
	<link rel="stylesheet" href="{% static './css/order.css' %}" />

	<!-- End CSS -->

	<title>Bar Stock Exchange</title>
</head>

<body class="homePageBody">
	<!-- ------------------------------------------- -->
	<!-- Start Header -->

	<header>
		<img class="logo" src="{% static '/images/Logo/cover.png' %}" alt="" />
	</header>

	<!-- End Header -->
	<!-- ------------------------------------------- -->
	<!-- Start Main -->

	<main class="homePage mainSection" id="homePage">
		<div class="search">
			<h3>What do you want to cook today?</h3>
			<div class="form">
				<input type="search" name="searchFood" id="searchFood" placeholder="Search For A Food Dish" />
				<button type="submit" id="submit">
					<img src="{% static '/images/search.png' %}" alt="" />
				</button>
			</div>
		</div>

		<div class="topHorizontal">
			<ul id="topHorizontal">
				<li onclick="changePannel(this, 'newest')" class="liEl active" id="newestLi">
					Newest Food
				</li>
				<li onclick="changePannel(this, 'recommended')" class="liEl">
					Chef's Recommended
				</li>
				<li onclick="changePannel(this, 'mostBid')" class="liEl">
					Best Bids
				</li>
			</ul>
		</div>

		<div class="foodHorizontal">

			<ul id="searched" class="pannel">
			</ul>

			<ul id="newest" class="pannel" style="display: block">
				{% for new in newest %}
				<a href="{% url 'showMenu' new.cuisine %}">
					<li>
						<div class="fooditem">
							<div class="foodPhoto">
								<img src="{% static '/images/Cuisines/'|add:new.cuisine|add:'.jpg' %}" alt="" />
							</div>
							<div class="content">
								<div class="like"></div>
								<div class="icon">
									<h4> ₹ {{ new.price }}</h4>
								</div>
								<section>
									<div class="bg-item"></div>
									<div class="bg-text">
										<div class="stars"></div>
										<h2>{{ new.name }}</h2>
										<h4>{{ new.cuisine }}</h4>
									</div>
								</section>
							</div>
						</div>
					</li>
				</a>
				{% endfor %}
			</ul>

			<ul id="recommended" class="pannel">
				{% for new in recommended %}
				<a href="{% url 'showMenu' new.cuisine %}">
					<li>
						<div class="fooditem">
							<div class="foodPhoto">
								<img src="{% static '/images/Cuisines/'|add:new.cuisine|add:'.jpg' %}" alt="" />
							</div>
							<div class="content">
								<div class="like"></div>
								<div class="icon">
									<h4> ₹ {{ new.price }}</h4>
								</div>
								<section>
									<div class="bg-item"></div>
									<div class="bg-text">
										<div class="stars"></div>
										<h2>{{ new.name }}</h2>
										<h4>{{ new.cuisine }}</h4>
									</div>
								</section>
							</div>
						</div>
					</li>
				</a>
				{% endfor %}
			</ul>

			<ul id="mostBid" class="pannel">
				{% for mostbid in recommended_drink %}
				<a href="{% url 'showBarMenu' mostbid.drinktype %}">
					<li>
						<div class="fooditem">
							<div class="foodPhoto">
								<img src="{% static '/images/Cuisines/'|add:mostbid.drinktype|add:'.jpg' %}" alt="" />
							</div>
							<div class="content">
								<div class="like"></div>
								<div class="icon">
									<h4> ₹ {{ mostbid.current_price }}</h4>
								</div>
								<section>
									<div class="bg-item"></div>
									<div class="bg-text">
										<div class="stars"></div>
										<h2>{{ mostbid.name }}</h2>
										<h4>{{ mostbid.drinktype }}</h4>
									</div>
								</section>
							</div>
						</div>
					</li>
				</a>
				{% endfor %}
			</ul>
		</div>
	</main>

	<!-- Explore Page Starts here -->
	<main class="explorePage mainSection" id="explorePage">
		<div class="explore heading">
			<span class="headingName">Explore</span>
		</div>
		<div class="topHorizontal">
			<ul>
				<li onclick="exploreSwitch(this, 'switchfood')" id="foodTab" class="exploreTab active">
					Food
				</li>

				<li onclick="exploreSwitch(this, 'switchdrink')" id="drinkTab" class="exploreTab">
					Drinks
				</li>
			</ul>
		</div>
		<div class="cuisinelisting">
			<div class="cusines food active" id="switchfood">
				{% for cuisine in allcuisine %}

				<a href="{% url 'showMenu' cuisine.cuisine %}">
					<div class="cuisine1">
						<div class="photo">
							<img class="cusinecover" src="{% static '/images/Cuisines/'|add:cuisine.cuisine|add:'-2.jpg' %}" alt="" />
						</div>
						<div class="label">
							<div class="bg-item"></div>
							<div class="label-cuisine">
								<h4>{{ cuisine.cuisine }}</h4>
							</div>

						</div>
					</div>
				</a>

				{% endfor %}
			</div>

			<div class="cusines drink" id="switchdrink">
				{% for drink in alldrinks %}

				<a href="{% url 'showBarMenu' drink.drinktype %}">
					<div class="cuisine1">
						<div class="photo">
							<img class="cusinecover" src="{% static '/images/Cuisines/'|add:drink.drinktype|add:'-2.jpg' %}" alt="" />
						</div>
						<div class="label">
							<h4>{{drink.drinktype}}</h4>
						</div>
					</div>
				</a>

				{% endfor %}
			</div>
		</div>
	</main>
	<!-- Explore Page Ends here -->

	<!-- ChatBot Page Starts here -->
	<main class="chatBotPage mainSection active" id="chatBotPage">
		<div class="intro">
			<h1>Bar Stock Exchange</h1>
			<span style="color: #3bb43b;">Online</span>
		</div>
		<div class="chattingArea messages-area">
			<br />
			{% for message in messages %}
			<div class="chat 
			    {{message.className}}">
				<p>
					{% for msg in message.message %}
					{% if msg == "|" %}
					<br>
					{% elif msg == " " %}
					&nbsp;
					{% else %}
					{{msg}}
					{% endif %}
					{% endfor %}
				</p>
			</div>
			<br />
			{% endfor %}
			<br />

			<!-- {% for i in allChat %}

			<div class="chat {{i.className}}">
				<p>{{i.text}}</p>
			</div>
			<br />

			{% endfor %} -->
		</div>
		<!-- <div class="input-area">
			<input type="text" id="message-input">
			<button id="send-btn">Send</button>
		</div> -->
		<div class="chatUser" id="chatButtons">
			<button class="noBtn" id="noBtn">
				<p>No</p>
			</button>
			<button class="yesBtn" id="yesBtn">
				<p>Yes</p>
			</button>
		</div>
	</main>
	<!-- chat Page Ends here -->

	<!-- Orders Page Starts here -->
	<main class="orderPage mainSection" id="orderPage">
		<!-- <div class="heading">
			<span class="headingName">Order</span>
		</div>

		<div class="orderGrid">
			<table cellspacing="10">
				<col width="45%" />
				<col width="1%" />
				<col width="30%" />
				<col width="40%" />
				<tr>
					<th>Dish Name</th>
					<th>Qty</th>
					<th></th>
					<th>Amount</th>
				</tr>

				{% for order in all_ordered %}
				<tr>
					<td>{{order.dish_name}}</td>
					<td>{{order.qty}}</td>
					{% if order.cooked %}
					<td class="eat"><span></span>Eat</td>
					{% else %}
					<td class="cook"><span></span>Cook</td>
					{% endif %}
					<td>
						<img src="{% static '/images/rupee.png' %}" alt="" />{{order.price}}
					</td>
				</tr>
				{% endfor %}
				<tr>
					<td>Tangerines Pancake</td>
					<td>2</td>
					<td class="prep"><span></span>Prep</td>
					<td>
						<img src="{% static '/images/rupee.png' %}" alt="" />249
					</td>
				</tr>

			</table>
			<div class="total">
				<h4>
					<img src="{% static '/images/rupee.png' %}" alt="" />5000
				</h4>
			</div>
		</div> -->
	</main>

	<!-- Orders Page Ends here -->

	<!-- End Main -->
	<!-- ------------------------------------------- -->
	<!-- Start Footer -->

	<footer>
		<div class="footerGrid">
			<li id="homeSlide" class="footerTab " onclick="footerSwitch(this, 'homePage')">
				<img src="{% static '/images/home.png' %}" alt="" />
				<img src="{% static '/images/home1.png' %}" alt="" />
				<span>Home</span>
			</li>
			<li id="exploreSlide" class="footerTab" onclick="footerSwitch(this, 'explorePage');">
				<img src="{% static '/images/explore.png' %}" alt="" />
				<img src="{% static '/images/explore1.png' %}" alt="" />
				<span>Explore</span>
			</li>
			<li id="chatSlide" class="footerTab active" onclick="footerSwitch(this, 'chatBotPage'); ChatOpen()">
				<img src="{% static '/images/chat.png' %}" alt="" />
				<img src="{% static '/images/chat1.png' %}" alt="" />
				<span>Chat</span>
			</li>
			<a href="{% url 'main:order' %}">
				<li id="orderSlide" class="footerTab" onclick="footerSwitch(this, 'orderPage')">
					<img src="{% static '/images/ordered.png' %}" alt="" />
					<img src="{% static '/images/ordered1.png' %}" alt="" />
					<span>Order</span>
				</li>
			</a>
		</div>
	</footer>

	<!-- End Footer -->
	<!-- ------------------------------------------- -->
	<!-- Add JS Files Here -->

	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

	<script>all_dishes = "{{ all_dishes }}";</script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/search.js' %}"></script>

	<script>
		let yesBtn = document.getElementById("yesBtn");
		let noBtn = document.getElementById("noBtn");

		function yes_message() {
			let message = "Deal";
			fetch("{% url 'chatroom-ajax' other_user.id %}",
				{
					method: "POST",
					credentials: 'same-origin',
					headers: {
						"Content-Type": 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify(message)
				}
			).then(e => e.json()).then(messages => {
				for (message of messages) {
					construct_message(message);
				}
			});
		}

		function no_message() {
			let message = "No Deal";
			fetch("{% url 'chatroom-ajax' other_user.id %}",
				{
					method: "POST",
					credentials: 'same-origin',
					headers: {
						"Content-Type": 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify(message)
				}
			).then(e => e.json()).then(messages => {
				for (message of messages) {
					construct_message(message);
				}
			});
		}

		/*
		function bot_message(msg) {
			let message = msg;
			fetch("{% url 'main:bot-message' other_user.id %}",
				{
					method: "POST",
					credentials: 'same-origin',
					headers: {
						"Content-Type": 'application/json',
						'X-CSRFToken': '{{ csrf_token }}'
					},
					body: JSON.stringify(message)
				}
			).then(e => e.json()).then(messages => {
				messages[0].sender = "foodmarket";
				messages[0].className = "bot";
			});
		}
		*/

		function load_messages() {
			fetch("{% url 'chatroom-ajax' other_user.id %}")
				.then(e => e.json()).then(messages => {
					for (message of messages) {
						construct_message(message);
					}
				})
		}

		function construct_message(message) {
			let messages_container = document.querySelector(".messages-area");
			if (message.sent) {
				className = "user_chat"
			}
			$('.user_chat').attr('data-attr', 'Mr. Green');

			let div = document.createElement("div");
			let br = document.createElement("br");
			console.log(message.className);
			div.classList.add("chat", message.className);
			div.innerHTML = `
							<p>${message.message}</p>
	        `
			messages_container.appendChild(div);
			messages_container.appendChild(br);
			div.scrollIntoView()
		}
		yesBtn.addEventListener('click', yes_message);
		noBtn.addEventListener('click', no_message);

		function cssChat() {
			$('.user_chat').attr('data-attr', '{{ request_user }}');
		}

		function disableButton() {
			var chatButtons = document.getElementById("chatButtons");
			chatButtons.classList.add("disable")
		}

		setInterval(cssChat, 100);
		setInterval(load_messages, 3500);
		// disableButton()

		// bot_message("Hey")
	</script>



	<!-- End JS -->
</body>

</html>

<!-- #A9A9A9 -->