Food_Stock_Exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as mainViews
from registration import views as registration


urlpatterns = [
    path('vv21/admin/', admin.site.urls),
    path('', include('web.urls')),
    path('register/', registration.registerPage, name="registration"),
    path('accounts/login/', registration.registerPage1, name="registration"),
    path('home/', include('main.urls')),
    path("home/<int:pk>/", mainViews.chatroom, name="chatroom"),
    path("home/ajax1/<int:pk>/", mainViews.ajax_load_messages, name="chatroom-ajax"),
    path("menu/<str:cuisine>", mainViews.showMenu, name="showMenu"),
    path("barmenu/<str:drinktype>", mainViews.showBarMenu, name="showBarMenu"),
    path("barmenu/ajax/<str:drinktype>", mainViews.showBarMenu_ajax, name="showBarMenu_ajax"),
]

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
  path("", views.project, name="project"),
  path("stock/", views.stock, name="stock"),
  path("stock/ajax", views.stock_load_ajax, name="stock_load_ajax"),
]

web/templates/web/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project | Bar Stock Exchange</title>

    <link rel="stylesheet" href="{% static '/css/landing.css' %}" />

</head>

<body>

    <header>

        <div class="logo">
            <img src="{% static '/images/Landing/logo.png' %}" alt="">
        </div>

        <nav></nav>
    </header>

    <main>

        <div class="title Slide">
            <div class="header">
                <h1>Bar Stock Exchange.</h1>
                <p id="info">The <b> Bar Stock Exchange </b> is a dine-in ordering web application for mobile devices
                    which helps people to order food or drinks in a club/restaurant.</p>


                <span id="read" onclick="readmore()">read more</span>
            </div>

            <!-- <div id="q" class="qrcode">
                <img src="{% static '/images/Landing/qr.jpg' %}" alt="">
            </div> -->


        </div>

        <div class="project Slide" id="project">
            <h2>Featured <b>projects.</b></h2>
            <p>Here are some Screenshots of our Web Application</p>

            <div class="gallery">
                <div class="big">
                    <img src="{% static '/images/Landing/feature-1.png' %}" alt="">
                </div>
                <div class="small">
                    <img src="{% static '/images/Landing/feature-2.png' %}" alt="">
                </div>
            </div>
            <br><br>
            <a href="#frameworks">view frameworks > </a>
        </div>

        <div class="features Slide">
            <h2>We are offering <b>unique solutions</b> to clients worldwide.</h2>
            <p>Here are some services we offer</p>

            <div class="slideshow">
                <div class="slides">
                    <div class="slide">
                        <div>
                            <div class="photo">
                                <img src="{% static '/images/Landing/infobox1.png' %}" alt="">
                            </div>
                            <h4>Front-End Solutions</h4>
                            <p>For Front-End Solution we use HTML, CSS, JavaScript, jQuery and ajax. It offers various
                                Styles and Design Patters which
                                helps to build a customizable Front-End according to users need.</p>
                        </div>
                        <div>
                            <div class="photo">
                                <img src="{% static '/images/Landing/infobox2.png' %}" alt="">
                            </div>
                            <h4>Mobile App Solutions</h4>
                            <p>We have made a Responsible Web - Application in our Project. You can scan the QR code to
                                see it.
                            </p>
                        </div>
                        <div>
                            <div class="photo">
                                <img src="{% static '/images/Landing/infobox3.png' %}" alt="">
                            </div>
                            <h4>Back-End Solutions</h4>
                            <p>For Developing Back-End of the Application we use Django as it is a customizable
                                framework, it offers best security and easy to use for administrative staff.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="used Slide" id="frameworks">
            <h2>These are the <b>frameworks</b> we have used in our Application.</h2>
            <br>
            <br>
            <div class="logos1">
                <img src="{% static '/images/Landing/logo-41.png' %}" alt="">
                <img src="{% static '/images/Landing/logo-31.png' %}" alt="">
                <img src="{% static '/images/Landing/logo-21.png' %}" alt="">
                <img src="{% static '/images/Landing/logo-51.png' %}" alt="">
            </div>
            <br>
            <br>
            <br><br><br>
            <div class="logos2">
                <img src="{% static '/images/Landing/logo-11.png' %}" alt="">
                <img src="{% static '/images/Landing/logo-61.png' %}" alt="">
                <img src="{% static '/images/Landing/logo-71.png' %}" alt="">
            </div>
        </div>

        <div class="features1 Slide">
            <div class="slideshow">
                <div class="slides">
                    <h1>Made By </h1>
                    <div class="names">
                        <div>
                            <h3>Vaibhav Patel</h3>
                            <div class="sociol">
                                <a href="https://github.com/Vaibhav-1904"><img
                                        src="{% static '/images/Landing/github.png' %}" alt=""></a>
                                <span></span>
                                <a href="https://www.linkedin.com/in/vaibhav-patel-05889b1a3/"><img
                                        src="{% static '/images/Landing/linkedin.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div>
                            <h3>Vrushit Patel</h3>
                            <div class="sociol">
                                <a href="https://github.com/Vrushit7506"><img
                                        src="{% static '/images/Landing/github.png' %}" alt=""></a>
                                <span></span>
                                <a href="https://www.linkedin.com/in/vrushit-patel/"><img
                                        src="{% static '/images/Landing/linkedin.png' %}" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>

    <footer>

        <div class="copyright">
            <span>© All right reserved 2021.</span>
            <span><a href="#">The Bar Stock Exchange</a></span>
        </div>


        <script>
            function readmore() {

                var information = document.getElementById("info");
                var r = document.getElementById("read");
                if (r.innerHTML == "read more") {
                    r.innerHTML = "read less";

                    information.innerHTML = "The Bar Stock Exchange is a dine-in ordering web application for mobile devices which helps people to order food or drinks in a club/restaurant. This software will be designed to increase restaurant customer interaction and not making them wait for the waiter to take their order. This software will be implementing a stock market theme for ordering the drinks. As in a stock market, more demand means higher prices similarly, the software should increase the price of the drink based on its demand.";
                } else {
                    information.innerHTML = "The Bar Stock Exchange is a dine-in ordering web application for mobile devices which helps people to order food or drinks in a club/restaurant. ";

                    r.innerHTML = "read more";
                }


            }
        </script>

    </footer>


</body>

</html>

web/templates/web/stock.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Bar Stock Exchange</title>

	<link rel="stylesheet" href="{% static '/css/styles.css' %}" />
	<link rel="stylesheet" href="{% static '/css/stock.css' %}" />

</head>

<body class="stockBody">

	<header>
		<img class="logo" src="{% static '/images/Logo/cover.png' %}" alt="" />
	</header>

	<table id="scrollStock">
		<tr>
			<th>Drink Type</th>
			<th>Drink Name</th>
			<th>Current Price</th>
			<th>Total Quantity</th>
			<th>Actual Price</th>
			<th>Savings</th>
			<th>Low</th>
			<th>High</th>
		</tr>

		{% for drink in all_drinks %}

		<tr>
			<td>{{drink.drinktype}}</td>
			<td>{{drink.name}}</td>
			<td class="{{drink.className}}">₹ {{drink.current_price}}</td>
			<td>{{drink.tot_qty}}</td>
			<td>₹ {{drink.actual_price}}</td>
			<td>{{drink.savings}}</td>
			<td>₹ {{drink.low}}</td>
			<td>₹ {{drink.high}}</td>
		</tr>

		{% endfor %}

		{% for drink in all_drinks %}

		<tr>
			<td>{{drink.drinktype}}</td>
			<td>{{drink.name}}</td>
			<td class="{{drink.className}}">₹ {{drink.current_price}}</td>
			<td>{{drink.tot_qty}}</td>
			<td>₹ {{drink.actual_price}}</td>
			<td>{{drink.savings}}</td>
			<td>₹ {{drink.low}}</td>
			<td>₹ {{drink.high}}</td>
		</tr>

		{% endfor %}

	</table>

	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

	<script>
		var scrollStock = document.getElementById("scrollStock");

		function scrollpage() {
			function f() {
				scrollStock.scrollTo(0, i);
				if (status == 0) {
					i = i + 0.2;
					if (i >= Height) {
						status = 1;
					}
				} else {
					scrollStock.scrollTo(0, 0);
					i = 0;
					status = 0;
				}
				setTimeout(f, 0.0001);
			}
			setTimeout(f, 2000);
		}

		var Height = scrollStock.offsetHeight + 1500;
		var i = 1, j = Height, status = 0;
		scrollpage();
	</script>

	<script>
		var scrollStock = document.getElementById("scrollStock");

		function getPage() {
			scrollStock.innerHTML = `
				<tr>
					<th>Drink Type</th>
					<th>Drink Name</th>
					<th>Current Price</th>
					<th>Total Quantity</th>
					<th>Actual Price</th>
					<th>Savings</th>
					<th>Low</th>
					<th>High</th>
				</tr>
			`
			fetch("{% url 'web:stock_load_ajax' %}")
				.then(e => e.json()).then(allorder => {
					for (order of allorder) {
						scrollStock.innerHTML += `
							<tr>
								<td>${order.fields.drinktype}</td>
								<td>${order.fields.name}</td>
								<td class="${order.fields.className}">₹ ${order.fields.current_price}</td>
								<td>${order.fields.tot_qty}</td>
								<td>₹ ${order.fields.actual_price}</td>
								<td>${order.fields.savings}</td>
								<td>₹ ${order.fields.low}</td>
								<td>₹ ${order.fields.high}</td>
							</tr>
						`
					}
				})
		}

		setInterval(getPage, 5000);
	</script>

</body>

</html>